### ISSUE TITLE
Write NTFS on Mac OS X

### ISSUE THREAD

**Issue by justmao945** [justmao945/justmao945.github.io#131]
http://learnaholic.me/2013/11/11/enable-ntfs-write-on-mac-os-x-mavericks/
http://www.tianwaihome.com/2014/07/mac-osx-ntfs.html

这是sb,太不安全了,非常容易让数据损坏.
OSX上就不要用什么NTFS了

**Comment by lythesia** [comment]
how to make tmpfs under osx?

**Comment by justmao945** [comment]
Why need tmpfs?

**Comment by lythesia** [comment]
I met some strange bugs with sparkr on my osx, I think it's related to tmp files (maybe).

**Comment by justmao945** [comment]
OK. What bug?

**Comment by lythesia** [comment]
booting very slow with a call inside JVM
