### ISSUE TITLE
cgdb

### ISSUE THREAD

**Issue by justmao945** [justmao945/justmao945.github.io#134]
http://cgdb.github.io/
gdb难用在哪?
不能一边看source一边操作...
虽然自带有一个TUI,但是那个东西好像不太好用,而且也没有高亮....
cgdb基本结束了这一切....

**Comment by lythesia** [comment]
any alternatives under osx (with clang)?

**Comment by justmao945** [comment]
xcode :sob:

**Comment by lythesia** [comment]
oh nooooooooo

**Comment by justmao945** [comment]
or you can fork to write a new UI based on lldb ?

**Comment by lythesia** [comment]
got one https://github.com/snare/voltron

**Comment by justmao945** [comment]
I had tried it last year, but don't know how to list source.

**Comment by lythesia** [comment]
just noticed that ... no source!

**Comment by lythesia** [comment]
finally compromised to gdb&cgdb, though with bunches of weird warnings ... (;´Д`)
btw, how to prevent the dSYM files generate during compling

**Comment by justmao945** [comment]
why to prevent dSYM? Is it something like .o ?
