### ISSUE TITLE
gem source

### ISSUE THREAD

**Issue by justmao945** [justmao945/justmao945.github.io#139]
When ruby is not compiled with OpenSSL, then it is unable to install gems from `gem`.
An error will be spawned  when run `gem install xxx`.
```
ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources
``` 

But we are still able to install gems with `http://` scheme.
First should remove the secure source `https://rubygems.org/`
```sh
gem source -r https://rubygems.org/
```

Then add http version source:
```sh
gem source -a http://rubygems.org/
```

**Comment by lythesia** [comment]
https://github.com/bpinto/oh-my-fish/issues/404
almost searched whole afternoon, no gain

**Comment by justmao945** [comment]
anything related to this issue ?
