### ISSUE TITLE
very very slow git pull

### ISSUE THREAD

**Issue by justmao945** [justmao945/justmao945.github.io#151]
* Problem: `git pull` is very very slow, may cost longer than 1 hour on server, but `git clone` is very fast. 
* Analysis: repo has many small files and changed very frequently, this may cause many git objects created under `.git/objects/` that slows down the system.
* Solution: run `git gc` more frequently, e.g. before every `git pull`

**Comment by lythesia** [comment]
I've never encounted this, so poor I am (without any big projects) :(

**Comment by justmao945** [comment]
The component owner is not me :laughing: , and most of small files are test files. Testing is really a hard work. :disappointed:

**Comment by justmao945** [comment]
In fact, `git gc` can't resolve this issue... Another reason may be caused the slow system call `lstat`. http://git-scm.com/docs/git-update-index
